name: Build

on:
  push:
    branches: ["master", "deploy"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: aviate-labs/setup-dfx@v0.2.4
        with:
          dfx-version: 0.12.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
